### ISSUE TITLE
PowerShell project launcher is not initialized with Validator

### ISSUE THREAD

**Issue by AndreSayreMSFT** [adamdriscoll/poshtools#176]
With the new validator, the PowerShell project launcher is not properly initialized when called from the Execute commands.  It constructs it via PowerShellProjectLauncher(), which doesn't check the validation, which then sees it as not being valid.

We should check the validation here & not silently fail

**Comment by adamdriscoll** [comment]
Will have to look at that!

**Comment by adamdriscoll** [comment]
Question about this issue. We are validating in the package that exposes those commands. 

![initialize](https://cloud.githubusercontent.com/assets/1256531/6181266/0561460a-b2f6-11e4-8760-4d2572274063.png)

If we don't call InternalInitialize, we won't add the commands to the Command Service. When you load up Visual Studio, the commands aren't visible anywhere. 

![no-executeasscript](https://cloud.githubusercontent.com/assets/1256531/6181276/296b7890-b2f6-11e4-9519-fc3a9ed0a5f2.png)

I think it's a bit of a code smell to rely on the caller to prevent the class from being called with the default constructor. What would you suggest be the fix for this be?

**Comment by AndreSayreMSFT** [comment]
Are we able to remove the Default constructor completely?  It's okay if it shows up in the context menu with the dependency validator prompting them about PS when the go to run it :)



![image](https://cloud.githubusercontent.com/assets/10080679/6222775/41cc4042-b60f-11e4-9d3a-6ac0f6bf5021.png)
