### ISSUE TITLE
The 'Describe' part is missing inside the Test Explorer

### ISSUE THREAD

**Issue by claudiospizzi** [adamdriscoll/poshtools#263]
It would be great, when the 'Describe' block could also be added to the Test Explorer. At the moment, only 'Context' and 'It' is shown, the 'Describe' part is missing. Maybe as prefix and/or even better, if we could group the tests by 'Describe' (like it's possible to group by classes in C#).

As an example, the following test code:
![image](https://cloud.githubusercontent.com/assets/1934246/7959010/5f240514-09f5-11e5-89a1-dd5fa8a0c39b.png)

And here the test inside the Test Explorer:
![image](https://cloud.githubusercontent.com/assets/1934246/7959044/bec8dc1a-09f5-11e5-8315-301f1b3a8949.png)

As you can see, the 'Describe' part is available in the tool tip, but not as a prefix of the test name or as an option to group by.
##

**Comment by adamdriscoll** [comment]
@claudiospizzi  Can you try this build? https://ci.appveyor.com/project/adamdriscoll/poshtools/branch/testadapter/artifacts

We have a pending PR that fixes a bunch of stuff in the test adapter. It corrects some issues with the integration. One of them being that Pester really is only capable of running tests at the Describe level and not individual Context\It blocks. So rather than discovering and running Context blocks, we now discover and run Describe blocks.

**Comment by adamdriscoll** [comment]
I also didn't realize the "Full Name" was shown in the UI at all (in the tooltip). I probably should pretty that up. ;)

**Comment by claudiospizzi** [comment]
I've installed the build you've provide me. With the same test as shown in my first post, now only the 'Describe' part is showing inside the Test Explorer as test name:

![image](https://cloud.githubusercontent.com/assets/1934246/8052798/18494236-0e8b-11e5-8779-3870a1c68a8f.png)

I would suggest to show all three parts, something like this:
[DescribeBlock]: [ContextBlock] It [ItBlock]

**Comment by adamdriscoll** [comment]
The reason it just shows describe blocks is because that's all that Pester is actually capable of running of invoking that granularity, I'll implement that support here. https://github.com/pester/Pester/issues/292
