### ISSUE TITLE
Signature verification failed during installation on VS2015 Community

### ISSUE THREAD

**Issue by JohnBravo** [adamdriscoll/poshtools#290]
During installation of Visual Studio 2015 Community edition I keep receiving the following error when including poshtools:

*PowerShell Tools for Visual Studio: This product did not download successfully: Signature verification failed on downloaded file.*

The log file shows this:

*MUX:  ExecuteError: Package (VSSecondaryInstaller_box) failed: Error Message Id: 1603 ErrorMessage: PowerShell Tools for Visual Studio : This product did not download successfully: Signature verification failed on downloaded file. URL:  'http://go.microsoft.com/fwlink/?LinkID=616995'*

As a workaround I could use the link to do a manual installation: http://go.microsoft.com/fwlink/?LinkID=616995

**Comment by jinglou-** [comment]
We have seen a similar report on failing to verify the certificate during the setup if the windows Update option to automatically update the root certificates is turned off. The error message was slightly different but it's possible this might be caused by the same issue.  Give the following a try to see if it fixes the issue you ran into:

Turn on the automatic update for root certificates by following these steps:
1.	Bring up the Run prompt by pressing Windows key + R
2.	Run gpedit.msc
3.	Navigate to: Local Computer Policy->Administrative Templates->System->Internet Communication Management->Internet Communication settings->Turn off Automatic Root Certificates Update
4.	Select “Disable” or “Not configured” to turn on the option
5.	Force a Windows Update to get the latest root certificates

Then try the VS setup again.
Hope this helps.

**Comment by JohnBravo** [comment]
Sorry for not replying earlier.
Your workaround worked! Thanks a lot.
