### ISSUE TITLE
Form item template not showing up

### ISSUE THREAD

**Issue by adamdriscoll** [adamdriscoll/poshtools#334]
For some, the form item template is not available in the New File dialog. 
##

**Comment by guidooliveira** [comment]
it only lists Script and module when creating a project from the template, but when i click on Add Item, Form is available, although even adding the assemblies, i can't seem to see the designer. Using VS 2015 Enterprise.

**Comment by gbianchi-ounet** [comment]
Hi, I was able to get the form to show up by copying the "PowerShell Form.zip" into the extension ItemTemplates folder (it was missing), but after adding the references specified in the video, when I double click on the form I get the following error: "The file 'C:\Users\Administrator\Documents\Visual Studio 2015\Projects\PowerShellFormTest\PowerShellFormTest\PowershellForm.ps1' does not support code parsing or generation because it is not contained within a project that supports code."

**Comment by ccondrup** [comment]
Thanks @gbianchi-ounet and of course @adamdriscoll  +1Same here, the file `PowerShell Form.zip` was not present in the folder `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\jya0fggy.3s3\ItemTemplates\`
I put the zip file there manually, restarted VS and then could see the new "Powershell Form" choice when adding a new item to my solution. Could it be a silly file name typo, since the other zips in the same folder don't have a space in the file name?

In the process of rewriting a bundle of Batch scripts in PowerShell and am hoping to make a nice GUI while at it. I'm really looking forward to XAML designer in poshtools, or some way to leverage poshtools when in a C# WPF solution.

**Comment by adamdriscoll** [comment]
@ccondrup Hmmm maybe it's an easy fix if it's just not getting copied. I've been slammed with work work so I have little time to look at this. 

Re: WPF - I actually threw up a branch awhile ago around this and just made a PR: https://github.com/adamdriscoll/poshtools/pull/388

Once the build finishes you should be able to try it out. You'll have to add a reference to PresentationFramework to get the designer to display. What I found was that it's a bit weird to wire up events. You can't do it in XAML because PowerShell doesn't compile to a binary the XAML designer understands so you need to do it in PowerShell. Some I'm not sure if it's possible to have the designer trigger a code generation for events because it edits the XAML which breaks the designer. Straightforward, I know. ;) 

One other little snag here is that there are bugs in the fork of the project system so the XAML designer isn't correctly hooked up to the code-behind in the Solution Explorer. I had to update fork which is massive code churn. Seems to be working fine but really needs some testing.

**Comment by adamdriscoll** [comment]
@ccondrup I tried renaming the template without the space and it seems to work for me. 

A new build should be available soon: https://github.com/adamdriscoll/poshtools/pull/330

**Comment by gbianchi-ounet** [comment]
@adamdriscoll I just tried the new build and still, the form template file did NOT get copied. once I added it by hand and the template showed up. I tried this on both win2012r2 and win10 with VS 2015 Community.
 
BTW I actually figured out why I couldn't edit the form from the designer, it was because I was using the build from the wrong branch (doh!) Can't wait to play around and build some GUIs for PS!!

**Comment by Nila-h** [comment]
Could anyone please help me how to get PowerShellForm running in Visual Studio 2015 com.
I followed the instructions aboven but I get still the error "The file 'C:\Users\Administrator\Documents\Visual Studio 2015\Projects\PowerShellFormTest\PowerShellFormTest\PowershellForm.ps1' does not support code parsing or generation because it is not contained within a project that supports code."

I have already add the reference according the video. 

I will be thankful for your help.

**Comment by mortasgus** [comment]
Two issues : The Form item template and displaying the Form designer without error.
I tried a lot of version and I have few references.
206, 208, 209 and 247 are ok for both issues
304 and 310 show only the designer from a previous script.

**Comment by adamdriscoll** [comment]
Implemented in the pro fools
