### ISSUE TITLE
PowerShellToolsProcessHost.exe starts for unclear reasons & does not stop

### ISSUE THREAD

**Issue by SamB** [adamdriscoll/poshtools#373]
So, um, I'm getting a bit tired of PowerShellProcessHost.exe starting up for no discernible reason and sticking around essentially forever; I really don't need to waste that 100MiB of RAM when I'm not doing anything PowerShell-related.

For example, right now I have Roslyn.sln open in VS 2015 Community, and only a few projects loaded from it.  There appear to be some PowerShell scripts in the repository, but certainly not in the loaded projects, and probably none in Roslyn.sln at all.  I haven't opened any PowerShell-related windows or done anything involving the Debugger.  But, for some reason, PowerShellToolsProcessHost.exe is running anyway.

So it would be nice if there were:

 1. Clear documentation on what situations can trigger it to start
 2. Some more user control over some of the more-easily-triggered ways it can be started, like whether it should be started to find out whether a given process is a viable target for PowerShell debugging *before* the user has shown any inclination that they'd like to attempt PowerShell debugging.
 3. Some sort of time-out mechanism so it doesn't stick around forever just because there was, at some point, a reason to want it around.

(I may be able to provide more specifics later, as I only just turned on the diagnostic logging option.)

**Comment by adamdriscoll** [comment]
I'll put all this in the wiki but the host will load pretty much whenever the PowerShell Tools package is loaded. This can happen for all kinds of reasons. 

1. Open/Create any type of PowerShell project
2. Open/Create PowerShell file(.ps1, .psm1, .psd1) from file->open/create or solution explorer
3. Execute PowerShell script file from solution explorer
4. Open the PowerShell interactive window (not the Package Manager console) 
5. Attach to process dialog 
6. Diffing PowerShell scripts

One way the console will load immediately, is that you have the interative window shown by default when loading Visual Studio. 

Warning the user could be done during package load with an option to cancel. Actions taken after that (such as IntelliSense or Debugging) would trigger the load since they are more explicit. This likely wouldn't be effective though if the interactive window were open as we run various commands to determine the correct prompt to display etc. I like the idea of a time out. We could make that configurable in the options. That would likely be the quickest fix to implement. 

Definitely open to suggestions on this. I hope logging provides a bit more insight into why your host is loading but since VS decides on package load we might not have a 100% clear picture from that log.
