### ISSUE TITLE
What is the current status of poshtools and the Microsoft fork?

### ISSUE THREAD

**Issue by gwojan** [adamdriscoll/poshtools#448]
Since there seems to be a lot more attention being paid to PowerShell in Visual Studio Code I was just wondering what the long term plans were for `poshtools` and the Microsoft fork.

I seem to recall reading somewhere that `poshtools` might actually start using `PowerShellEditorServices`. Did I really see this or am I completely losing it in my old age? :wink: 
##

**Comment by adamdriscoll** [comment]
I had mentioned that I had the intention of converting PoshTools to utilize PowerShellEditorServices but it's a pretty big conversion process which I haven't had the time to work on. It will be the direction I hope to take this project though so that PoshTools can benefit from all the goodies that VSCode is receiving.
