### ISSUE TITLE
What's the proj file intended usage?

### ISSUE THREAD

**Issue by StingyJack** [adamdriscoll/poshtools#544]
The readme.md [screenshot](https://camo.githubusercontent.com/21b38e6635e12e2889c527ef6c32a5df0879c1c5/687474703a2f2f692e696d6775722e636f6d2f4637446f3361642e706e67)  depicts a bunch of  `.ps1` files. 

I've been using a single project with a subfolder for each module. The property pages for the project appear to be geared towards a single module per project.  The way I'm using it is working, but I do get odd problems with the project from time to time and curious to know if I'm using it in a way that was not intended, or the property pages are available to be used but not necessary.

**Comment by adamdriscoll** [comment]
@StingyJack The property pages aren't necessary for what you are doing. The project file isn't all that useful at the moment except for organizing your stuff. There are some things in the issue backlog to use those property pages to generate manifests for modules or things that are similar to that. The project system could also be used to support cross script code analysis and IntelliSense but that hasn't been developed. 

So if what you are doing is working for you, it's totally cool since you aren't loosing out on much. There are now Pre\Post build events you can use to run scripts during the "build" but there's no reason you couldn't take advantage of that with your current configuration.

**Comment by StingyJack** [comment]
The build events will def be useful. Thanks for the info.
